spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: "true"
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&useUnicode=true&serverTimezone=Asia/Seoul
  #  sql:
  #    init:
  #      data-locations: classpath:db/data/data.sql
  #      mode: always
  #      platform: mysql
  #      encoding: UTF-8

  jpa:
    generate-ddl: "true"
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: "true"
        show_sql: "true"
    database: mysql
    defer-datasource-initialization: "true"
    show-sql: "true"

